version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn install && yarn test 
      - run: yarn add lighthouse-ci
      - run: yarn add lighthouse
      - run: lighthouse https://your.md 
      - run: lighthouse-ci --performance=40 https://your.md 
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
