version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn build
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: lighthouse-ci --performance=40 https://your.md
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test