version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn install && yarn test 
  perfTests:
    parallelism: 2
    docker:
      - image: guiguidu31300/lighthouse-ci

    steps:
      - checkout

      - run:
          name: Run lighthouse against production deployment

          environment:
            TEST_URL: https://your.md

          command: |
            lighthouse-ci $TEST_URL --performance=30

      - persist_to_workspace:
          root: /home/chrome
          paths:
            - reports
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - perfTests

